#!/bin/sh

rcup -v -K config/zsh/{.zlogin,.zlogout,.zshrc,.zshenv,.zprofile}

if [ ! -d ~/.config/nvim/pack/minpac/opt/minpac ]; then
  git clone https://github.com/k-takata/minpac.git \
    ~/.config/nvim/pack/minpac/opt/minpac
fi

if [ "$SHELL" == "/bin/zsh" ] && [ ! -d ~/.zplug ]; then
  curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
  ~/.zplug/bin
fi

if [ ! -d ~/.rbenv ]; then
  curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash

  echo "Load rbenv (init)\n"
  ~/.rbenv/bin/rbenv init

  echo "Available (MRI) versions:\n"
  ~/.rbenv/bin/rbenv install --list | \grep -Ev "rbx|jruby|maglev|mruby|ree|truffle|topaz" | tail

  echo 'rbenv install version'
fi
