#!/bin/sh

rcup -v -K config/zsh/{.zlogin,.zlogout,.zshrc,.zprofile}

if [ ! -d ~/.config/nvim/pack/minpac/opt/minpac ]; then
  git clone https://github.com/k-takata/minpac.git \
    ~/.config/nvim/pack/minpac/opt/minpac
fi
